### ISSUE TITLE
Shortening Code

### ISSUE THREAD

**Issue by ldo** [zschumacher/pydapper#100]
Seems to me you still leave it to the caller to create a cursor for every query. I like to shorten this with a generator function like (taken from [here](https://github.com/ldo/python_topics_notebooks/blob/master/Databases%2C%20Iterators%20%26%20Looping.ipynb)):

    def db_iter(conn, cmd, mapfn = lambda x : x) :
        "executes cmd on a new cursor from connection conn and" \
        " yields the results in turn."
        for item in conn.cursor().execute(cmd) :
            yield mapfn(item)
        #end for
    #end db_iter

Then queries become as simple as

    for row in db_iter(conn, "select ...") :
        ... do something with row ...
    #end for

Also, instead of providing “buffered” versus “unbuffered” versions of queries, why not just provide the iterator (“unbuffered”) version; then returning the entire query list is as simple as

    buffered_result = list(unbuffered_query())

Finally, I have a technique for providing both synchronous and asynchronous variants of an API with minimal code duplication. You can see it in action [here](https://github.com/ldo/seaskirt).

**Comment by zschumacher** [comment]
Can you please move this to a discussion? I’d like any open issues to be direct calls for features/improvements and this seems pretty open ended.
