### ISSUE TITLE
Returning data from "RETURNING" clause of INSERT

### ISSUE THREAD

**Issue by osirispt** [zschumacher/pydapper#123]
Using SQLite, i want to send a group of objects into the database and receive the inserted ones while the existing ones are ignored.

For than, i can use "... ON CONFLICT ... DO NOTHING RETURNING ...".

I've tried to do it with pydapper but i can't seem to get it to work. The data gets inserted but `execute` always returns zero.

Am i doing something wrong or is this unsupported by pydapper?
It seems to be unsupported but i may be wrong, hence my question.

Example code below:

```python
import pydapper
from dataclasses import dataclass

@dataclass
class Person:
	id: int
	name: str
	address: str
	phone: int
	
	def __init__(self, name, address, phone):
		self.name = name
		self.address = address
		self.phone = phone

def do_something():
	people = [Person('Alice', 'Here', 1111), Person('Bob', 'There', 2222)]
	with pydapper.connect("sqlite://example.sqlite3") as commands:
		new_records = commands.execute(
			"INSERT INTO PEOPLE (name, address, phone) values (?name?, ?address?, ?phone?) ON CONFLICT(phone) DO NOTHING RETURNING *",
			param=people,
		)
		print(new_records)

```

**Comment by zschumacher** [comment]
execute only returns the number of affected rows - I can think about how to implement returning and see if its something dapper supports for inspiration.  As you said though, this is currently unsupported.

**Comment by zschumacher** [comment]
you could do it with query, but query doesn't currently support a list of params

**Comment by zschumacher** [comment]
Would you mind linking the dapper examples you found? I looked briefly but didn’t find much

**Comment by zschumacher** [comment]
it seems like that example is only inserting/updating a single row, isn't it?

**Comment by zschumacher** [comment]
right - I actually think you'd want a bulk insert for what you're trying to do, as the current execute uses execute many of the python dbapi, which typically makes one trip to the database but executes the inserts one by one.  This means that the cursor would only actually have the last result of the returning * anyway. 

At some point I'd like to add a bulk operations api similar to dapper plus, but haven't got around to it yet.

**Comment by zschumacher** [comment]
Django has a `return_models` kwarg on their bulk operations, so I can dig into that for some inspiration, though I'd guess they issues multiple queries to accomplish that

**Comment by zschumacher** [comment]
can I close this?  I think we settled on its not something that is supported right now, but will be supported in the future with a bulk api
