### ISSUE TITLE
How to document a CASCADE

### ISSUE THREAD

**Issue by ssweber** [zschumacher/pydapper#127]
Maybe this is a dumb question.

I see the ‘Serialize a one-to-one relationship’. How would I mark it not only as a foreign key, but, eg SQLite “On UPDATE CASCADE”?

thank you!

**Comment by zschumacher** [comment]
I'm not sure I understand your question.  Can you provide a code example with how the code behaves versus what you would expect?

**Comment by zschumacher** [comment]
I'm going to close this as there hasn't been any activity
