### ISSUE TITLE
Custom column mapping

### ISSUE THREAD

**Issue by FabricioAraujoRJ** [zschumacher/pydapper#194]
I have an existing DB and want to try pydapper - since I already use Dapper.NET in C#. 
But how to  custom map columns (and, if possible, ignore) columns on classes?

**Comment by zschumacher** [comment]
Can you give an example of what you’re trying to do? Pseudo code is fine

**Comment by FabricioAraujoRJ** [comment]
In Dapper.Net(C#) I can do: 
```
[Table("ALUNO")]
class Student:
{
    [Column(Name="NOME_DESCRICAO")]
    string Name {get;set;}
}
```
And the table "ALUNO" (Portughese for Student) maps for Student class and the property Name maps to column  "NOME_DESCRICAO" (Portughese  equivalent of "NAME_DESCRIPTION" ).

**Comment by zschumacher** [comment]
Ah got it, pydantic pairs really well with pydapper.  https://docs.pydantic.dev/latest/.  With pydantic you could do something like 

```python
import pydantic

class Student(pydantic.BaseModel):
    name_description: str = pydantic.Field(alias="name")
```

**Comment by FabricioAraujoRJ** [comment]
So, using pydantic.Field makes pydapper automatically map to required field?
Example:

`
SQL:
create table dbo.Task
(
 task_id: int,
 name_description: varchar(50),
 due_datetime: datetime,
 ownerid: int
)


import datetime
from dataclasses import dataclass

from pydapper import connect


@dataclass
class Task:
    id: int = pydantic.Field(alias="task_id")
    description: str = pydantic.Field(alias="name_description")
    due_date: datetime = pydantic.Field(alias="due_datetime")
    owner_id: int = pydantic.Field(alias="ownerid")


with connect() as commands:
    data = commands.query("select * from task limit 1", model=Task)

print(data)
# [Task(id=1, description='Set up a test database', due_date=datetime.date(2021, 12, 31), owner_id=1)]
`
This would work? How I would map the table if, instead of task, it's called tasks (in plural)?

**Comment by zschumacher** [comment]
Closing this, feel free to reopen if you still have questions
