### ISSUE TITLE
✨ Add first class support for sprocs

### ISSUE THREAD

**Issue by cemmerven** [zschumacher/pydapper#29]
A little more samples please
I'm struggling to call MSSQL stored procedure(s) with parameter(s)
like 
create or alter procedure sp_TestCall(   @foo int,   @bar nvarchar(10) ) AS
BEGIN
   select 
      @foo + 1  as Id, 
      GETDATE() as ServerTime 
END

as dictionary-as-a-paramter-list ( my expectation is from the original .NET based dapper an anonymous type as-a-parameter-list )  :
...
 with pydapper.connect( "mssql://bunny:carrot@192.168.1.148:1433/CarrotMSDB") as commands:
     # commands.query_first( "sp_TestCall", param= { "foo": 1, "bar": U"some text" } )
     # commands.query_first( "execute sp_TestCall", param= { "foo": 1, "bar": U"some text" } )
     # commands.query_first( "execute sp_TestCall @foo, @bar", param= { "@foo": 1, "@bar": U"some text" } )
     # commands.query_first( "execute sp_TestCall @foo, @bar", param= { "foo": 1, "bar": U"some text" } )

    # commands.query_first( "execute sp_TestCall", param = dict( foo= 1, bar= U"some text" )  )

and many more combinations of the above...

always ends with:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pydapper/utils.py", line 11, in safe_getattr
    return obj[key]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/QueryValidCards.py", line 240, in CardPass
    result = commands.query_first( "execute sp_TestCall", param= { "foo": 1, "bar": U"some text" } )
  File "/usr/local/lib/python3.7/dist-packages/pydapper/commands.py", line 188, in query_first
    handler.execute(cursor)
  File "/usr/local/lib/python3.7/dist-packages/pydapper/commands.py", line 83, in execute
    cursor.execute(self.prepared_sql, self.ordered_param_values)
  File "/usr/local/lib/python3.7/dist-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.7/dist-packages/pydapper/commands.py", line 75, in prepared_sql
    return pattern.sub(sub_param_with_placeholder, self._sql)  # type: ignore
  File "/usr/local/lib/python3.7/dist-packages/pydapper/commands.py", line 73, in sub_param_with_placeholder
    return self.get_param_placeholder(matched_param_name)
  File "/usr/local/lib/python3.7/dist-packages/pydapper/mssql/pymssql.py", line 26, in get_param_placeholder
    param_value = safe_getattr(test_param, param_name)
  File "/usr/local/lib/python3.7/dist-packages/pydapper/utils.py", line 16, in safe_getattr
    raise KeyError(f"Key {key!r} can not be accessed on {obj!r} or does not exist")
KeyError: "Key '' can not be accessed on {'foo': 1, 'bar': 'some text'} or does not exist"

**Comment by zschumacher** [comment]
Thanks for the issue! I’ll dig into this a bit and try to add some stored proc calls to the docs/test suite

**Comment by zschumacher** [comment]
this is taking a bit longer as calling sprocs doesn't "just work".  Per the db api for procs, I need to think about how I can provide an interface for [callproc](https://peps.python.org/pep-0249/#callproc).  Which feels more natural?

Note that in pydapper, you pass params as `?paramname?` as opposed to the `@Param` used by dapper.

Option 1
```python
with pydapper.connect() as commands:
    commands.query_proc("MyProc ?param1? ?param2?", params={"param1": "Hello", "param2": "world"}
```

Option 2
```python
with pydapper.connect() as commands:
    commands.query("MyProc ?param1? ?param2?", params={"param1": "Hello", "param2": "world", proc=True}
```

**Comment by zschumacher** [comment]
it would be great to get some others input on this as well, esp if you have had experience using dapper directly.  Tagging a few below..

@troyswanson 
@deasko
@JonTheTurnip
@otosky
@bruce-dunwiddie

**Comment by bar** [comment]
@cemmerven I'm pretty sure you didn't mean to tag me, right?

**Comment by bruce-dunwiddie** [comment]
> this is taking a bit longer as calling sprocs doesn't "just work". Per the db api for procs, I need to think about how I can provide an interface for [callproc](https://peps.python.org/pep-0249/#callproc). Which feels more natural?
> 
> Note that in pydapper, you pass params as `?paramname?` as opposed to the `@Param` used by dapper.
> 
> Option 1
> 
> ```python
> with pydapper.connect() as commands:
>     commands.query_proc("MyProc ?param1? ?param2?", params={"param1": "Hello", "param2": "world"})
> ```
> 
> Option 2
> 
> ```python
> with pydapper.connect() as commands:
>     commands.query("MyProc ?param1? ?param2?", params={"param1": "Hello", "param2": "world"}, proc=True)
> ```

Option 2 is how I've seen it done in many languages, including core .Net classes, where it's just called through the same method, but specifying a "command type":

- https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtype?view=dotnet-plat-ext-6.0

- https://www.learndapper.com/stored-procedures

pyodbc apparently just depends on the "EXEC" syntax, https://code.google.com/archive/p/pyodbc/wikis/StoredProcedures.wiki , which seems to match up to @cemmerven 's second syntax attempt above:

`commands.query_first( "execute sp_TestCall", param= { "foo": 1, "bar": U"some text" } )`

**Comment by JonTheTurnip** [comment]
Hi all, I haven't thought about this too much but I think I'm also more in favor of option 2,  I can't see any obvious problems with that approach.

**Comment by zschumacher** [comment]
thanks for the feedback - I think I will implement a `CommandType` enum and corresponding `command_type` kwarg on relevant methods

**Comment by zschumacher** [comment]
in the mean time @cemmerven, this should work for you with the current release 

```python
commands.query_first( "execute sp_TestCall ?foo? ?bar?", param = dict(foo=1, bar="some text" ))
```

**Comment by zschumacher** [comment]
I still plan to work on this, I've just had a busy month.  Plan to pick this up in the next week or so.

**Comment by zschumacher** [comment]
after trying multiple different solutions, I ultimately couldn't find something that work well in python without being kind of awkward for at least one of the DBMS' that pydapper supports.  The reality is that `callproc` is inconsistently implemented across the various dbapis, and because of that its hard to come up with a consistent interface that works for everything.

For now, I'm not planning on putting this into a future release, but I will plan to continue to think on it.

The below will work on all pydapper methods, however and is the solution I recommend in the interim.   As @bruce-dunwiddie mentioned, this is the path that pyodbc took for the same reason.

```python
with pydapper.connect(MSSQL_URI) as commands:
    result = commands.query("EXEC GetTaskById @Id = ?id?", param={"id": 1})
```
