### ISSUE TITLE
how to connect to sql server using windows authentication

### ISSUE THREAD

**Issue by JonTheTurnip** [zschumacher/pydapper#30]
Hi there, I'm a big dapper fan so good to see this project in Python!

I need to use windows auth to connect to a database server on the coporate network.  The problem is that I'm not finding anywhere that pymssql supports this?  I've tried to use pyodbc as per the below but that doesn't seem to work.  Any help much appreciated, I'm new to Python.

![image](https://user-images.githubusercontent.com/10959562/183023392-449fd712-e86f-4602-a15a-b030ce33d391.png)

**Comment by zschumacher** [comment]
pyodbc is not yet supported, but it is on my roadmap to add

**Comment by zschumacher** [comment]
It does look like pymssql should support it though https://pymssql.readthedocs.io/en/stable/pymssql_examples.html#connecting-using-windows-authentication

**Comment by zschumacher** [comment]
you can see how the DSN gets passed into pymmsql's entry point [here](https://github.com/zschumacher/pydapper/blob/main/pydapper/mssql/pymssql.py#L32) or alternatively just use it directly and pass the conn obj into `pydapper.using
`

**Comment by JonTheTurnip** [comment]
@zschumacher - thanks for getting back, much appreciated.  Apologies again that my Python skills are not that great!

As far as I can tell the potential problem with pymssqI for my use case is that it will require users at some point to type their windows password in plaintext into a script, and inevitably they'll accidentally end up checking their username/password into a repository  or sharing a script with their password in an email, or something like that.

I've never used the windows DSN option before, looks fairly straightforward and avoids the accidental password sharing problem but introduces an extra step in the process, i.e someone has to make sure they set a DSN up before they can use the script.

With pyodbc, and c#/.net when you use windows auth somehow your current user credentials are passed behind the scenes without you having to enter them at all, that's ultimately what I'm looking for.

Hope that all makes sense?  I'd like to offer to help with your pyodbc support but I'm not their yet, not sure I will be anytime soon as I'm mainly working on .net stuff, but you never know.
